config/routes.rb
Rails.application.routes.draw do
    root 'decks#index'
    resources 'decks' do
      resources 'rounds', only: 'create'
    end

    resources 'rounds' do
      resources 'cards'
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :rounds
  has_many :cards
end

app/models/round.rb
class Round < ApplicationRecord
  # belongs_to :user
  belongs_to :deck
end

app/models/user.rb
class User < ApplicationRecord
   has_secure_password
   validates :password, :length => {:minimum => 5}
   validates :username, :email, presence: true, uniqueness: true
   has_many :rounds


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @card = Card.find(params[:id])
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = Deck.all
  end

  def show
    @deck = Deck.find(params[:id])
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def create
    @round = Round.create(deck_id: params[:deck_id])
    redirect_to [@round, @round.deck.cards.first]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/show.html.erb
<p> <%=@card.deck.name%> </p>

<p><%= @card.question%></p>

app/views/decks/index.html.erb
# build my decks index view

<ul>
  <% @decks.each do |deck| %>
    <li><%= link_to deck.name, deck %></li>
    <!-- <li>deck.whatever</li> -->
  <% end %>
</ul>

app/views/decks/show.html.erb
<h1> <%= @deck.name.capitalize%> </h1>

<h3> <%= @deck.description%> </h3>

<%= button_to "Play!", deck_rounds_path(@deck)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>